// <auto-generated />
namespace Training4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201603152116279_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
